# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      otel:
        patterns:
          - "go.opentelemetry.io/otel*"
      otel-collector:
        patterns:
          - "go.opentelemetry.io/collector*"
          - "github.com/open-telemetry/o*-collector-contrib/*"
      otel-instrumentation:
        patterns:
          - "go.opentelemetry.io/contrib/instrumentation/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
