name: "Build and test"
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ (github.event.pull_request && github.event.pull_request.number) || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - uses: actions/checkout@v3

    - name: "run test in all go modules"
      run: make gotest
