name: "Basic checks"
on: [push, pull_request]

jobs:
  basic-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18'

    - uses: actions/checkout@v3

    - name: "run test in all go modules"
      run: make gotest

